{{- if .Values.litellm.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webui.fullname" . }}-litellm-config
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "webui.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.litellm.config | nindent 4 }}
{{- end }}