{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "webui.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "webui.labels" . | nindent 4 }}
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if .Values.persistence.selector }}
  selector: {{- toYaml .Values.persistence.selector | nindent 4 }}
  {{- end }}
  {{- if .Values.persistence.dataSource }}
  dataSource: {{- toYaml .Values.persistence.dataSource | nindent 4 }}
  {{- end }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
{{- end -}}
