{{- if and .Values.openai.enabled ( not .Values.openai.existingApiKeySecret ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webui.fullname" . }}-openai-api-key
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "webui.labels" . | nindent 4 }}
type: Opaque
data:
  openai-api-key: {{ .Values.openai.apiKey | b64enc | quote }}
{{- end }}